swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Accounts List
      description: API for fetching a list of accounts
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
            $ref: '#/definitions/AccountList'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Transactions List
      description: API for fetching a list of transactions
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionList'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/{id}:
    put:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Edit Transaction
      description: API for updating a transaction
      parameters:
        - in: path
          name: id
          type: string
          description: Numeric ID of the transaction to edit
          required: true
        - in: body
          name: body
          description: Update transaction information
          required: true
          schema:
            $ref: '#/definitions/TransactionEdit'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction edited successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    description: User object containing user details
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    description: Login object containing login details
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    description: API response object
    type: object
    properties:
      status:
        type: integer
        description: status code
      message:
        type: string
        description: status message
      body:
        type: object
        description: response body
        properties:
          id:
            type: string
            description: user ID
          email:
            type: string
            description: user email
  LoginResponse:
    description: Login response object containing token
    type: object
    properties:
      token:
        type: string
        description: authentication token
  UserProfile:
    description: User profile object containing username
    type: object
    properties:
      userName:
        type: string
        description: user public name
  AccountList:
    description: List of user accounts
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          description: account ID
        name:
          type: string
          description: account name
        balance:
          type: string
          description: account balance
  TransactionList:
    description: List of user transactions
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          description: transaction ID
        id_account:
          type: string
          description: account ID
        date:
          type: string
          description: transaction date
        description:
          type: string
          description: transaction description
        amount:
          type: string
          description: transaction amount
        balance:
          type: string
          description: account balance after transaction
        type:
          type: string
          description: transaction type 
        category:
          type: string
          description: transaction category
  TransactionEdit:
    description: Transaction edit object
    type: object
    properties:
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: transaction note
  TransactionResponse:
    description: Transaction response object
    type: object
    properties:
      id:
        type: string
        description: transaction ID
      id_account:
        type: string
        description: account ID
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: string
        description: transaction amount
      balance:
        type: string
        description: account balance after transaction
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      note:
        type: string
        description: transaction note